[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0.4"
actix-web = "^4"
actix-multipart = "^0.6"
futures-util = "^0.3"
validr = "^0.3"
serde = "^1"
serde_json = "^1"
chrono = "^0.4"
mime = { version = "^0.3" }

auth = { path = "../auth" }
config = { path = "../config" }
context = { path = "../context" }
cryptfns = { path = "../cryptfns" }
entity = { path = "../entity" }
error = { path = "../error" }
util = { path = "../util" }

[dev-dependencies]
context = { path = "../context", features = ["mock"] }
entity = { path = "../entity", features = ["mock"] }
async-std = { version = "^1", features = ["attributes", "tokio1"] }
