name: Publish Docker image

# on:
#   release:
#     types: [published]

on:
  # Trigger the workflow on every branch
  push:
    branches:
      - "master"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Read the crate version
        run: echo "CARGO_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_ENV

      - name: rust sccache
        uses: pl-strflt/rust-sccache-action@v1.1.1

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/hoodik
          tags: ${{ env.CARGO_VERSION }}

      - name: Generate .env
        run: |
          echo "APP_VERSION=${{ env.CARGO_VERSION }}" >> $PWD/.env
          echo "APP_NAME=Hoodik" >> $PWD/.env

      - name: Loading the configuration from
        run: ls -la && cat "$PWD/.env" && export ENV_FILE="$PWD/.env" && node --version

      - name: Install os dependencies
        run: sudo apt install curl libpq-dev clang llvm pkg-config nettle-dev libc6-dev -y

      - name: Install wasm pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install yarn
        run: npm install -g yarn

      - name: Install yarn dependencies
        run: yarn install

      - name: Wasm pack
        run: yarn wasm-pack

      - name: Release all
        run: yarn release:all

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.tag }} , ${{ secrets.DOCKER_USERNAME }}/hoodik:latest

          labels: ${{ steps.meta.outputs.labels }}
