name: Test

on:
  # Trigger the workflow on every branch
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Loading the configuration from
        run: cat "$PWD/.env.e2e" && export ENV_FILE="$PWD/.env.e2e"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pkg-config
        run: sudo apt install curl libpq-dev clang llvm pkg-config nettle-dev libc6-dev -y

      - name: Install wasm pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install yarn
        run: npm install -g yarn

      - name: Install yarn dependencies
        run: yarn install

      - name: Wasm pack
        run: yarn wasm-pack

      - name: Run unit tests
        run: yarn unit

      - name: Run e2e tests
        run: yarn e2e
