name: Test-Rust

on:
  # Trigger the workflow on every branch
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pkg-config
        run: sudo apt install -y clang llvm pkg-config nettle-dev

      - name: Run yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run unit tests
        uses: borales/actions-yarn@v4
        with:
          cmd: unit

      - name: Run e2e tests
        uses: borales/actions-yarn@v4
        with:
          cmd: e2e
