name: Test

on:
  # Trigger the workflow on every branch
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pkg-config
        run: sudo apt install -y clang llvm pkg-config nettle-dev

      - name: Run yarn install
        run: npm install -g yarn && yarn install

      - name: Run unit tests
        run: yarn unit

      - name: Run e2e tests
        run: yarn e2e
